### ISSUE TITLE
docker 网页版本点击无法跳转，会直接新开页面白屏

### ISSUE THREAD

**Issue by kokojacket** [TinkMingKing/siyuan-plugins-index#13]
<img width="1824" alt="微信截图_20230609102008" src="https://github.com/TinkMingKing/siyuan-plugins-index/assets/74887370/aa80af75-5798-436f-a045-83ef6a7f2c99">

**Comment by TinkMingKing** [comment]
块链接如果在网页端打开，会调用桌面端来跳转，由于使用docker端的用户在本地通常不会去安装siyuan所以无法跳转导致白屏，说是bug也不算bug吧，下个版本支持使用`引用块`来创建目录，docker用户推荐使用这个选项

**Comment by kokojacket** [comment]
> 

明白了 谢谢

**Comment by TinkMingKing** [comment]
开发者说这个问题已经修复，看来不是特性而是bug，所以这个功能可能不做，等后续发版，更新到思源最新版应该就正常了
