### ISSUE TITLE
希望支持配置，可选不插入文档图标

### ISSUE THREAD

**Issue by MoonBottle** [TinkMingKing/siyuan-plugins-index#24]
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/12904505/8a001859-4612-49a9-a64b-40bfa5dd7ad5)

大部分文档使用的是默认图标，感觉不是很美观，希望可以配置选择不插入图标

**Comment by TinkMingKing** [comment]
有没有一种可能是已经支持了，只需要把为数不多的三行说明看完就能够明白如何去设置

**Comment by MoonBottle** [comment]
抱歉抱歉
