### ISSUE TITLE
目录折叠可以有吗

### ISSUE THREAD

**Issue by yylicon** [TinkMingKing/siyuan-plugins-index#26]
大佬，目录以列表的形式嵌套，默认是全部展开的，手动折叠后，下次刷新又变成全部展开了。可以支持设置默认展开到第几层或者刷新的时候记忆上次折叠情况呢？
参考了语雀的目录设置：
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/124042427/fce3be76-eef8-4b1c-a330-0b58f8331033)

**Comment by TinkMingKing** [comment]
自动更新会重置目录，除非关闭自动更新目录，折叠后才会保存状态，设置默认折叠层级没考虑过，有空看看

**Comment by TinkMingKing** [comment]
看了一下，想要保留折叠状态只能关闭自动更新，如果要另外实现不大可能，下个版本可以支持设置默认展开层级
