### ISSUE TITLE
恕我愚钝

### ISSUE THREAD

**Issue by a18ccms** [TinkMingKing/siyuan-plugins-index#3]
实在是没用明白。请问安装完怎么使用？右键，斜杠。怎么也没找到怎么生成。

**Comment by TinkMingKing** [comment]
![Screenshot_20230515_152551.png](https://github.com/TinkMingKing/siyuan-plugins-index/assets/32903588/db8ef50f-8ca5-44d0-bdef-d6ba4793e152)
