### ISSUE TITLE
docker 中更新时，README.md的权限好像有问题，导致更新失败

### ISSUE THREAD

**Issue by RogerHuHu** [TinkMingKing/siyuan-plugins-index#35]
![WeChatdfdc4e538340a12229124db33c074ac5](https://github.com/TinkMingKing/siyuan-plugins-index/assets/3404169/ece676d9-13d8-42e7-8fc1-bfc90957cddb)

**Comment by TinkMingKing** [comment]
我感觉不是系统问题就是软件问题，一个文本文件通常不会产生这种问题，有点玄学，后续更新可能自己就好了
