### ISSUE TITLE
针对于网页版部署，插入的目录存在问题。

### ISSUE THREAD

**Issue by ba0gu0** [TinkMingKing/siyuan-plugins-index#37]
### 问题

> 在网页版部署后，目录点击后会跳转app，打开失败。

<img width="852" alt="image" src="https://github.com/TinkMingKing/siyuan-plugins-index/assets/19379443/b3ce7551-8854-4407-b071-fcb49d737b6c">

> 尝试过使用右键修改，转换成引用，但是刷新后又恢复成私有协议了。

<img width="411" alt="image" src="https://github.com/TinkMingKing/siyuan-plugins-index/assets/19379443/e474921b-bed9-4a66-99f6-d8aa9d198b8d">

### 分析

> 在客户端中，直接使用链接的方式，指向siyuan私有协议，可以实现跳转

> 比如  siyuan://blocks/20230821154024-xpgggfh

> 最终生成的代码为：

` [Untitled](siyuan://blocks/20230821154024-xpgggfh)`

> 但是在网页中，使用siyuan私有协议会跳转到app中，最终又打开app

> 实际上在siyuan中，引用链接 使用的代码格式为

` ((20230821154024-xpgggfh "Untitled"))`

> 希望可以适配一下网页版。

> 
>

**Comment by TinkMingKing** [comment]
不是问题，是特性
右键点击图标，设置链接类型为块引用即可

**Comment by ba0gu0** [comment]
了解，设置改好了
