### ISSUE TITLE
切换布局时候会导致图标重复

### ISSUE THREAD

**Issue by JARVISia** [TinkMingKing/siyuan-plugins-index#38]
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/16850140/cf88ce01-a824-41b7-8179-c3d3e4042f3a)

**Comment by JARVISia** [comment]
> ![image](https://user-images.githubusercontent.com/16850140/268658382-cf88ce01-a824-41b7-8179-c3d3e4042f3a.png)


![0553bdc54571bc0872b45852c4a84078](https://github.com/TinkMingKing/siyuan-plugins-index/assets/16850140/415e123c-f3eb-4939-a4bc-2214b2b90023)
跟这个插件存在冲突

![5a7385e1ef42d982cc01a2e89b1bf3a6](https://github.com/TinkMingKing/siyuan-plugins-index/assets/16850140/93da5a1b-d5ee-46d7-ad5c-9b639374b486)
关掉设置的第一项即可

**Comment by pisceswb** [comment]
自己折腾了好久，来这儿终于找到原因了
