### ISSUE TITLE
开头为 ' 文档名的文档插入目录会失败

### ISSUE THREAD

**Issue by gaoluji** [TinkMingKing/siyuan-plugins-index#39]
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/139356383/a9c9bcf7-cad8-43df-9725-4a0b2dcd69d4)
不知道是否能够完善？

**Comment by TinkMingKing** [comment]
短期没空修复

**Comment by TinkMingKing** [comment]
要改的不多，在github的codespace里搞定了，不然得等几个月
