### ISSUE TITLE
目录聚焦导致思源崩溃

### ISSUE THREAD

**Issue by tongzi001** [TinkMingKing/siyuan-plugins-index#42]
https://ld246.com/article/1697439951478
这个github有时候很难打开，建议在思源笔记上开通一个反馈渠道。
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/148167517/7f6dfbf5-b91c-4391-80a8-971a9d074b21)

**Comment by TinkMingKing** [comment]
暂时无法解决，先移除自动更新的功能

**Comment by TinkMingKing** [comment]
修复了，等1.4.7更新，再试试会不会造成问题，要启用自动更新选项
