### ISSUE TITLE
自动匹配文档名（标题）

### ISSUE THREAD

**Issue by tongzi001** [TinkMingKing/siyuan-plugins-index#44]
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/148167517/914989d3-3cb7-4a9c-ba55-7eb69ce5048b)
当较多的文档粘贴到思源的时候，还要逐一复制粘贴文档名，有时候效率不高。能否一键提取文档的第一行内容，将其匹配到文档名栏？

**Comment by TinkMingKing** [comment]
直接使用思源的浏览器剪藏插件，或者webclipper就行了

**Comment by tongzi001** [comment]
哦 好的 有空试试
