### ISSUE TITLE
块引用or超链接？

### ISSUE THREAD

**Issue by silverbullet1472** [TinkMingKing/siyuan-plugins-index#48]
感谢作者！
想请教一下有没有计划添加使用**块引用**来生成目录的计划？
因为目前使用超链接的话，好像在关系图中间就不会生成链接。
举例：
我的**知识管理**文档下有子文档**思源笔记学习**，我在**知识管理**中插入目录后，自然的就把下面的内容和知识管理连接了。
我觉得这样好像比插入双链接更好啊？
因为我刚刚了解双链笔记的概念，可能有些偏差。不知道作者你是怎么考虑的？

**Comment by TinkMingKing** [comment]
右键点击图标有相关设置项，请仔细阅读集市文档中的使用说明



---原始邮件---
发件人: "Jiaqi ***@***.***&gt;
发送时间: 2023年12月10日(周日) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TinkMingKing/siyuan-plugins-index] 块引用or超链接？ (Issue #48)




 
感谢作者！
 想请教一下有没有计划添加使用块引用来生成目录的计划？
 因为目前使用超链接的话，好像在关系图中间就不会生成链接。
 举例：
 我的知识管理文档下有子文档思源笔记学习，我在知识管理中插入目录后，自然的就把下面的内容和知识管理连接了。
 我觉得这样好像比插入双链接更好啊？
 因为我刚刚了解双链笔记的概念，可能有些偏差。不知道作者你是怎么考虑的？
