### ISSUE TITLE
提取大纲引用可选【复制文本*】

### ISSUE THREAD

**Issue by AvoidantPerDis** [TinkMingKing/siyuan-plugins-index#50]
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/154863885/dfe80791-a3ba-4701-acd7-8bb9b8b23c5b)
提取完的大纲是引用块，难以添加样式

**Comment by TinkMingKing** [comment]
是说想支持`文本*`的样式？

**Comment by AvoidantPerDis** [comment]
对

**Comment by AvoidantPerDis** [comment]
好用，谢谢大佬
