### ISSUE TITLE
非空文档插入目录时的警告

### ISSUE THREAD

**Issue by tongzi001** [TinkMingKing/siyuan-plugins-index#55]
当用户在已有内容的文档中插入目录，这个时候能否做个判断，就是：非空文档原则上禁止插入目录，以免破坏原有资料。

这个时候给个警告提示，提醒用户新建空白文档，然后在空白文档中插入目录。
![image](https://github.com/TinkMingKing/siyuan-plugins-index/assets/148167517/98a921df-b8f7-4471-9125-6d968275f191)

**Comment by TinkMingKing** [comment]
不考虑这样做
