### ISSUE TITLE
块引用 bug，退出聚集再进去 右上角提示未找到id为xx的内容块，看视频

### ISSUE THREAD

**Issue by lsb226** [TinkMingKing/siyuan-plugins-index#57]
![20240516_152949](https://github.com/TinkMingKing/siyuan-plugins-index/assets/16093704/3ca4a2ef-b399-4b33-b7d5-b3d615418265)

**Comment by lsb226** [comment]
实测 手动复制引用都是可以的，没有这个bug 应当是插件的问题

**Comment by TinkMingKing** [comment]
是否开启了自动更新，可能是自动更新导致的，可能暂时没办法解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月16日(周四) 下午3:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [TinkMingKing/siyuan-plugins-index] 块引用 bug，退出聚集再进去 右上角提示未找到id为xx的内容块，看视频 (Issue #57)




 
实测 手动复制引用都是可以的，没有这个bug 应当是插件的问题

**Comment by TinkMingKing** [comment]
思源本体的问题，索引没有及时更新

https://github.com/TinkMingKing/siyuan-plugins-index/assets/32903588/2ffb027e-dd98-4da2-828e-f7fd54fb22cd
